# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heatherr', '0003_auto_20160211_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('user_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('interval', models.CharField(blank=True, choices=[(b'daily', b'Daily'), (b'weekly', b'Weekly')], max_length=255)),
                ('last_checkin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slackaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heatherr.SlackAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CheckinItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slackaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heatherr.SlackAccount')),
            ],
        ),
    ]
