# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
