# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_checkin_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinitem',
            name='slackaccount',
        ),
        migrations.DeleteModel(
            name='CheckinItem',
        ),
    ]
