# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255)),
                ('incoming_webhook_url', models.CharField(max_length=255)),
                ('incoming_webhook_channel', models.CharField(max_length=255)),
                ('incoming_webhook_configuration_url', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(max_length=255)),
                ('bot_access_token', models.CharField(max_length=255)),
            ],
        ),
    ]
