# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255)),
                ('incoming_webhook_url', models.CharField(max_length=255)),
                ('incoming_webhook_channel', models.CharField(max_length=255)),
                ('incoming_webhook_configuration_url', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(max_length=255)),
                ('bot_access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
