# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatherr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackaccount',
            name='bot_checkin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='slackaccount',
            name='bot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackaccount',
            name='bot_status',
            field=models.CharField(choices=[(b'online', b'Online'), (b'offline', b'Offline')], default=b'offline', max_length=255),
        ),
    ]
