# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatherr', '0002_auto_20160211_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackaccount',
            name='bot_status',
            field=models.CharField(choices=[(b'connecting', b'Connecting'), (b'online', b'Online'), (b'offline', b'Offline'), (b'error', b'Error')], default=b'offline', max_length=255),
        ),
    ]
