# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heatherr', '0003_auto_20160211_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackaccount',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
