# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:12
from __future__ import unicode_literals

from django.db import migrations


def move_fk_to_m2m(apps, schema_editor):
    SlackAccount = apps.get_model('heatherr', 'SlackAccount')

    for slackaccount in SlackAccount.objects.all():
        slackaccount.users.add(slackaccount.user)
        slackaccount.save()


class Migration(migrations.Migration):

    dependencies = [
        ('heatherr', '0004_slackaccount_users'),
    ]

    operations = [
        migrations.RunPython(move_fk_to_m2m),
    ]
