# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatherr', '0005_auto_20160228_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='slackaccount',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
