# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatherr', '0006_auto_20160228_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackaccount',
            name='bot_error_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slackaccount',
            name='bot_error_message',
            field=models.TextField(blank=True),
        ),
    ]
