# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heatherr', '0003_auto_20160211_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acronym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(blank=True, max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('slackaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heatherr.SlackAccount')),
            ],
        ),
    ]
