# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20151222_1202'),
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slackaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SlackAccount'),
        ),
        migrations.AddField(
            model_name='person',
            name='slackaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SlackAccount'),
        ),
    ]
