# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_auto_20151224_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slackaccount',
        ),
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='person',
            name='slackaccount',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
