# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slackaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bellman.SlackAccount'),
        ),
        migrations.AlterField(
            model_name='person',
            name='slackaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bellman.SlackAccount'),
        ),
    ]
