# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heatherr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('slackaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heatherr.SlackAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(to='groups.Group')),
                ('slackaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heatherr.SlackAccount')),
            ],
        ),
    ]
